---
version: 1.0.0
slug: viewu_server
name: Viewu Server
description: A Viewu Server in Home Assistant Add-on form.
url: https://github.com/Pooppap/viewu_server_ha_addon
arch:
  # - aarch64
  - amd64
auth_api: true
discovery:
  - mqtt
# image: mjeoffline/viewu:{arch}
# map:
#   - ssl
#   - share
options:
  logins: []
  # require_certificate: false
  # certfile: fullchain.pem
  # keyfile: privkey.pem
  # customize:
  #   active: false
  #   folder: mosquitto
ports:
  1883/tcp: 1883
  # 1884/tcp: 1884
  # 8883/tcp: 8883
  # 8884/tcp: 8884
schema:
  logins:
    - username: str
      password: password
      password_pre_hashed: "bool?"
  # require_certificate: bool
  # certfile: str
  # cafile: str?
  # keyfile: str
  # customize:
  #   active: bool
  #   folder: str
  debug: bool?
services:
  - mqtt:need
startup: application
watchdog: tcp://[HOST]:1883
init: false